import { Layout } from "@/components/Layout";
import { PhoneBookProvider } from "@/context/phoneBook.context";
import "./globals.css";

export const metadata = {
  title: "Phone Book",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <Layout>
          <PhoneBookProvider>{children}</PhoneBookProvider>
        </Layout>
      </body>
    </html>
  );
}
